### ISSUE TITLE
Give an argparse for the model selection as well. 

### ISSUE THREAD

**Issue by nadzhou** [duolinwang/MusiteDeep#6]

**Comment by nadzhou** [comment]
Instead of automatically loading the model hard-coded we can work on making it an argparse. Here's the total error: 
```

Traceback (most recent call last):
  File "predict_batch.py", line 184, in <module>
    main()         
  File "predict_batch.py", line 89, in main
    predictproba=batch_predict(testfrag,models,model,nclass,outputfile)
  File "predict_batch.py", line 28, in batch_predict
    models.load_weights(model+'_class'+str(bt))
  File "/home/nadzhou/anaconda3/envs/phospho/lib/python2.7/site-packages/keras/engine/topology.py", line 2616, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/nadzhou/anaconda3/envs/phospho/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/nadzhou/anaconda3/envs/phospho/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = './models/models_ST_HDF5model_class_class0', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by duolinwang** [comment]
It already has that argarse, please follow the instructions in readme file for advanced users. It is -model-prefix.
